### ISSUE TITLE
Extended Copy Menu (fix version)

### ISSUE THREAD

**Issue by TMMC** [kashiif/copy-urls-expert#11]
I currently use your extension Copy Urls Expert and Extended Copy Menu (fix version): [http://mzl.la/1yQjt9g](http://mzl.la/1yQjt9g).
Do you think it's possible to add Extended Copy Menu functions to Copy Urls Expert? Maybe as an option? 
I know these are two different add-ons, but maybe it's possible as they both work on selection and copying options? I ask because my Firefox is dying from add-ons overload and I think I'm not the only one, so having two merged into one seems a good option ;)

**Comment by kashiif** [comment]
Could not do it in 2 years. Wont fix

**Comment by TMMC** [comment]
All right, it's great add-on anyways :)
