### ISSUE TITLE
Choose format from menus

### ISSUE THREAD

**Issue by qoxxxx** [kashiif/copy-urls-expert#14]
If I'm not mistaken, in order to switch format you have to go every time to the addon's option menu and then set the default format ?

It would be nice to have access to all defined formats from the right-click menu.

**Comment by kashiif** [comment]
I've been thinking on this.

One possible solution is have a separate menu item in context menu called "All formats". That would have something as follows:

```
Copy Urls Expert 
             |---------------- ...
             |---------------- All Formats
                                           |---------------- Tabs in this window
                                                                             |---------------- html
                                                                             |---------------- forum
                                           |---------------- Tabs in all windows
                                                                             |---------------- html
                                                                             |---------------- forum
                                           |---------------- Tabs in this tag group
                                                                             |---------------- html
                                                                             |---------------- forum
                                           |---------------- Current Tab
                                                                             |---------------- html
                                                                             |---------------- forum

```

Where "html" and "forum" are the names of two styles defined (other than default format)

**Comment by kashiif** [comment]
The problem with above solution is it makes menu complicated. 

The other solution that I have in my mind is to add a "Advanced Copy" menu item. When you click on it, a dialog pops up and it lets you select one of the defined formats and one of the options for what tabs to copy (active window, all windows, active tag group etc.). IN the future I can add more customization options to this dialog.

To me, this seems simpler. Only the people interested in advanced copy, would use that menu and everything remain the same for a normal user.

What do you think? Or if you ahve any suggestion, I would like to hear it.

**Comment by Gitoffthelawn** [comment]
I like the idea of keeping it simple for day-to-day use, and then having advanced options for the unique cases.

**Comment by qoxxxx** [comment]
I was thinking of that kind of complicated tree, but I like the popup menu idea better actually.

**Comment by atomGit** [comment]
+1 for a context menu of available formats

for users that think this is too complex, you could copy with the default format and only expose the menu of all available formats with a hot-key when clicking the parent ("Tabs in ...") menu, however if this is how it get implemented, i would hope for an option to always show the formates menu by default (without having to press a hot-key)

**Comment by Avierling** [comment]
an alternative is have a Lite version

**Comment by kashiif** [comment]
The code has been pushed to ADVANCE_COPY branch. If anyone would like to test and provide feedback, I can provide xpi (that can be installed in nightly).

**Comment by Keith94** [comment]
@kashiif Some feedback:

* Typos need fixing: Advance >> Advanced, Clipborad >> Clipboard

* Template menu seems to have no available options? (tested in Nightly)

* If I assign Advanced Copy to toolbar button default action, it doesn't work.

**Comment by kashiif** [comment]
@Keith94 

> If I assign Advanced Copy to toolbar button default action, it doesn't work.

This is now fixed in ADVANCE-COPY branch. With this, I have completed all items for the next release (v2.6.0). Feel free to create a new issue if you find anything. 

Thank you for your valuable feedback.
