### ISSUE TITLE
Tab Groups (Panorama) Deprecation

### ISSUE THREAD

**Issue by CodeWaggle** [kashiif/copy-urls-expert#15]
Hi Kashif,

I just found your "Copy Urls Expert" plugin and intended to use the "Tabs In This Tab Group" functionality.

But shortly after I installed it I came across this notice from Mozilla:
[Discontinuing the Tab Groups feature](https://support.mozilla.org/en-US/kb/tab-groups-removal)

A new add-on, [Tab Groups Add-on](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/), was created directly from the Firefox tab groups (Panorama) code, so I'm wondering if you'll continue to support the "Tabs In This Tab Group" functionality for use with the new "Tab Groups" add-on?

Thank You for your time and effort in providing "Copy Urls Expert",
Joe Schmitt

**Comment by kashiif** [comment]
I have tested Copy Urls Expert 2.5.0 with Tab Group extension in the latest nightly (FF 49?). Everything seems to be working. Unless there is a very major change required, I will try to keep the compatibility.
