### ISSUE TITLE
LICENSE file is empty

### ISSUE THREAD

**Issue by purpleidea** [kashiif/copy-urls-expert#17]
https://github.com/kashiif/copy-urls-expert/blob/master/LICENSE file is empty. I suggest adding a LICENSE, GPLv3+ is a good suggestion. Other good licenses exist too.

Thanks

**Comment by ian-kelling** [comment]
+1. I'd like to include this project in the free software directory, but I can't tell that it's free software. https://directory.fsf.org/wiki/Main_Page. Even more important than putting something in the license file is a notice in the readme or the license file stating the license that all files are under. Right now, some have no license header.
