### ISSUE TITLE
Remove redirection urls in selected links

### ISSUE THREAD

**Issue by MUFTAKiS** [kashiif/copy-urls-expert#21]
how to do that??!

**Comment by kashiif** [comment]
This is something  copy urls expert does not do neither claims to do it. It could be nice to have especially when copying urls from selection.

**Comment by MUFTAKiS** [comment]
i didnt understand anything from you english plz, here is an example:

http://www.example.com/en/redirect.php?url=https%3A%2F%2Fsafelinking.net

- do you see 1st part of url this is what i want to remove from the links and just copy the 2nd part of url 
- also i want to fix %% in urls
- got it??!!

**Comment by kashiif** [comment]
It is not possible to that using Cooy Urls Expert

**Comment by MUFTAKiS** [comment]
i see, do you know any addon on firefox do this :)
