### ISSUE TITLE
Migrate to WebExtensions

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#25]
Can this add-on be implemented using the new [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) API?

**Comment by kashiif** [comment]
v3.0.0 or a fork would be based on web-extensions.

**Comment by Gitoffthelawn** [comment]
Any progress?

**Comment by Keith94** [comment]
Some here: https://github.com/kashiif/copy-urls-expert-web-extension/tree/pilot

**Comment by Gitoffthelawn** [comment]
Great!  Thanks!

**Comment by Gitoffthelawn** [comment]
@kashiif Do you think you'll have a WebExtensions version approved by Firefox 57?

**Comment by kashiif** [comment]
Gitoffthelawn : I did start working on it but finding very less time (and motivation) to work on it. I am afraid I won't be able to complete it by FX57.

**Comment by Gitoffthelawn** [comment]
@kashiif That's too bad, but I do appreciate you letting me know. :)

If you find the time to work on it, just let us know. :)

**Comment by Gitoffthelawn** [comment]
BTW, have been searching for a WebExtension-compatible extension that can copy and paste URLs and have been unable to find one.  If anyone knows of one, please recommend!

**Comment by Keith94** [comment]
I use these two for copying and pasting if that helps

https://addons.mozilla.org/firefox/addon/copy-all-tab-urls-we/
https://addons.mozilla.org/firefox/addon/open-multiple-urls/

**Comment by Gitoffthelawn** [comment]
@Keith94 Thank you!  I found those two as well.

They work well, but neither works from the context menu. :(

Also, the second one doesn't look good when placed in the menu panel. :(

But better than nothing! :)

If the authors put them on GitHub, they could be improved efficiently.

**Comment by Keith94** [comment]
Yeah or check out https://github.com/wantora/multiple-paste-and-go-button

**Comment by Gitoffthelawn** [comment]
@Keith94 Thank you!  That works great from the menu panel. :)
