### ISSUE TITLE
Options window is truncated

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#28]
Opening the options window in Nightly 53 looks like this initially:

![firefox_2016-12-20_01-42-09](https://cloud.githubusercontent.com/assets/5490615/21345565/9f4fc1a0-c655-11e6-9789-cc41f0d22bab.png)

**Comment by kashiif** [comment]
How did you fix it?

**Comment by Keith94** [comment]
Just clicking on one of the tabs (General, etc.) will show the full window temporarily.

**Comment by kashiif** [comment]
I got it reproduced consistently. This happens only the first time when CUE options window is loaded after Firefox restart. The issue disappears if I disable Keybinder extension. Looks like Keybinder tries to examine every xul window. Maybe you could report it to Keybinder repo.

Here is the screenshot of error log:

![2016-12-27_09h52_36](https://cloud.githubusercontent.com/assets/1826380/21487469/af3df6ae-cc1d-11e6-901a-6fb8e2f5c0ac.png)

**Comment by Keith94** [comment]
I reported it, thanks!

**Comment by Lord-Kamina** [comment]
Hello, I'm the Keybinder developer. I'll take a look at this, although by design keybinder should only be looking at windows designated as main browser windows.
