### ISSUE TITLE
A couple typos in options

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#30]
Please check these typos in the options text:

https://github.com/kashiif/copy-urls-expert/search?q=feautre&type=Code&utf8=%E2%9C%93
"feautre" should be "feature"

https://github.com/kashiif/copy-urls-expert/search?q=charcater&type=Code&utf8=%E2%9C%93
"charcater" should be "character"

**Comment by kashiif** [comment]
Fixed in ADVANCE-COPY branch
