### ISSUE TITLE
Open All Urls In Selection is broken

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#31]
Using the add-on in Nightly, attempting to use "Open All Urls In Selection" feature with some urls selected, doesn't open them as expected. In the Browser Console shows this error:

`TypeError: copyUrlsExpert._getEntriesFromSelection is not a function[Learn More]  copyurlsexpert.js:309:19`

**Comment by Keith94** [comment]
It seems this bug was introduced after I installed the latest version from ADVANCE_COPY branch.

**Comment by Keith94** [comment]
It also affects opening urls from clipboard as well? According to this:

`ReferenceError: createTransferable is not defined[Learn More]  copyurlsexpert.js:434:9`

**Comment by kashiif** [comment]
This should be fixed now in ADVANCE_COPY branch

**Comment by Keith94** [comment]
Confirmed fixed.
