### ISSUE TITLE
Add toolbar button to nav bar by default

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#33]
When installing the add-on for the first time, add CUE's button directly to the navigation bar, so users can discover it and won't have to move it manually to use it. Majority of add-ons already do this by default.

**Comment by kashiif** [comment]
Fixed

**Comment by Keith94** [comment]
Can confirm. Description on AMO can be updated too:

>Copy Urls Expert Toolbar button (You will have to add button manually. How to add button?)
