### ISSUE TITLE
TypeError: templates is null

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#35]
In 2.6.0 build (and previous ones), the template menu doesn't work.

```
TypeError: target is null[Learn More]  copyurlsexpert.js:491:13
TypeError: templates is null[Learn More]  advanced.js:65:20
```

![firefox_2016-12-30_17-08-35](https://cloud.githubusercontent.com/assets/5490615/21574964/c1dcc7a8-ceb2-11e6-9a6a-f12649bfa22b.png)

**Comment by kashiif** [comment]
Can you please try with KeyBinder disabled or in a new firefox profile? I think Keybinder is affecting all XUL-based windows.

**Comment by Keith94** [comment]
Yeah, I can reproduce this in a fresh profile with no other add-ons (Nightly 53 on Windows 8)

**Comment by kashiif** [comment]
User environment issue
