### ISSUE TITLE
WebExtensions question

### ISSUE THREAD

**Issue by lenisko** [kashiif/copy-urls-expert#46]
Will this extension be supported by Firefox 57 + versions?

https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

**Comment by kashiif** [comment]
The web-extension will be a separate extension. The repository is [here](https://github.com/kashiif/copy-urls-expert-web-extension/tree/webpack-setup). At the moment I have implemented the Copy Tab URLs function and will be submitting it to AMO within two weeks.
